ALTER TYPE "EnquiryStatus" RENAME VALUE 'IN_PROGRESS' TO 'IN_DISCUSSION';
ALTER TYPE "EnquiryStatus" RENAME VALUE 'COMPLETED' TO 'CONVERTED';
ALTER TYPE "EnquiryStatus" RENAME VALUE 'ARCHIVED' TO 'CLOSED';
