import { ArrowRight, Handshake, Lightbulb, MoveUpRight, UsersRound } from 'lucide-react';
import HeroCarousel from '@/components/hero-carousel';
import ServicesCarousel from '@/components/services-carousel';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';

export default function Home(){
 return <main>
    <SiteHeader />
  <HeroCarousel/>
  <ServicesCarousel/>

  <section id="work" className="bg-[var(--viridian-950)] py-24 text-white"><div className="container-xl"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-bold tracking-[.25em] text-[var(--gold)]">WHAT WE BRING TO THE TABLE</p><h2 className="mt-4 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">From opportunity to action.</h2></div><p className="max-w-md text-sm leading-6 text-white/60">A few of the ways JLUXE supports its clients, partners and communities across different services.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4"><article className="bg-[var(--viridian-950)] p-8"><Lightbulb className="h-7 w-7 text-[var(--gold)]"/><h3 className="mt-12 font-display text-2xl">Create</h3><p className="mt-3 text-sm leading-6 text-white/60">Build ideas, brands and spaces with purpose.</p></article><article className="bg-[var(--viridian-950)] p-8"><UsersRound className="h-7 w-7 text-[var(--gold)]"/><h3 className="mt-12 font-display text-2xl">Connect</h3><p className="mt-3 text-sm leading-6 text-white/60">Bring people and opportunities into the same conversation.</p></article><article className="bg-[var(--viridian-950)] p-8"><Handshake className="h-7 w-7 text-[var(--gold)]"/><h3 className="mt-12 font-display text-2xl">Support</h3><p className="mt-3 text-sm leading-6 text-white/60">Provide practical support across business and professional needs.</p></article><article className="bg-[var(--viridian-950)] p-8"><MoveUpRight className="h-7 w-7 text-[var(--gold)]"/><h3 className="mt-12 font-display text-2xl">Grow</h3><p className="mt-3 text-sm leading-6 text-white/60">Help people and organisations take their next step.</p></article></div></div></section>

  <section className="bg-[var(--sand)]/35 py-24"><div className="container-xl grid gap-10 md:grid-cols-[.85fr_1.15fr] md:items-center"><div><p className="text-xs font-bold tracking-[.25em] text-[var(--gold)]">REAL ESTATE</p><h2 className="mt-4 font-display text-4xl leading-tight text-[var(--viridian-950)] sm:text-5xl">Looking to buy or sell?</h2><p className="mt-5 max-w-lg leading-7 text-[var(--muted)]">JLUXE works as a channel partner, helping property owners and developers market opportunities while connecting them with potential buyers.</p><a href="/services/real-estate" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[var(--viridian-900)] px-6 py-3 text-sm font-semibold text-white">Explore Real Estate <ArrowRight className="h-4 w-4"/></a></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[var(--viridian-900)] p-7 text-white"><p className="text-xs tracking-[.2em] text-[var(--gold)]">FOR BUYERS</p><h3 className="mt-10 font-display text-3xl">Find the right opportunity.</h3><p className="mt-3 text-sm leading-6 text-white/60">Share your requirement and let us understand what you're looking for.</p></div><div className="rounded-3xl bg-white p-7"><p className="text-xs tracking-[.2em] text-[var(--gold)]">FOR SELLERS</p><h3 className="mt-10 font-display text-3xl text-[var(--viridian-950)]">Put your property forward.</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Tell us about your plot or property and explore working with JLUXE.</p></div></div></div></section>

  <section id="contact" className="bg-[var(--viridian-900)] py-20 text-white"><div className="container-xl flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold tracking-[.25em] text-[var(--gold)]">LET&apos;S TALK</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Have a requirement in mind?</h2><p className="mt-3 text-white/60">Tell us what you need. We&apos;ll help you find the right next step.</p></div><a href="/contact" className="inline-flex w-fit items-center gap-2 rounded-full bg-[var(--cream)] px-7 py-3.5 text-sm font-semibold text-[var(--viridian-950)]">Contact JLUXE <ArrowRight className="h-4 w-4"/></a></div></section>

  <SiteFooter />
 </main>
}
